In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier 

In [3]:
df = pd.read_csv("Student.csv")

In [4]:
df

Maths  CS Result
0      4   3      F
1      6   7      P
2      7   8      P
3      5   5      F
4      8   8      P

In [5]:
X = df.iloc[:, :-1].values
y = df.iloc[:, 2].values

In [6]:
X

array([[4, 3],
       [6, 7],
       [7, 8],
       [5, 5],
       [8, 8]], dtype=int64)

In [7]:
# y=np.array([[6,8],[3,4],[7,7],[3,2],[7,9]])
# y

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)

In [9]:
knn = KNeighborsClassifier(n_neighbors = 2)

In [10]:
knn = knn.fit(X_train, y_train)

In [11]:
predictions = knn.predict(X_test)

In [12]:
print(predictions)

['P' 'F']


In [13]:
X_test

array([[8, 8],
       [5, 5]], dtype=int64)

In [14]:
y_test

array(['P', 'F'], dtype=object)

In [15]:
X_train

array([[4, 3],
       [7, 8],
       [6, 7]], dtype=int64)

In [16]:
y_train

array(['F', 'P', 'P'], dtype=object)